example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here

from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_mywatchlist
from mywatchlist.views import show_xml
from mywatchlist.views import show_json
from mywatchlist.views import show_html


app_name = 'mywatchlist'

urlpatterns = [
    path('', show_mywatchlist, name='show_mywatchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('html/', show_html ,name='show_html'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/',include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
   
]

# TODO: Implement Routings Here

todolist/urls.py
from todolist.views import delete, register #sesuaikan dengan nama fungsi yang dibuat
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import create_task
from todolist.views import show_todolist
from todolist.views import update_task
from todolist.views import delete
from todolist.views import add_todolist_item
from todolist.views import get_todolist_json
from django.urls import path

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),  
    path('login/',login_user, name='login'),
    path('logout/',logout_user, name='logout'),
    path('create-task/', create_task, name='create-task'),
    path('update-task/<int:id>/',update_task,name='update-task'),
    path('delete-todolist/<int:id>/',delete,name='delete-todolist'),
    path('json/', get_todolist_json,name='get-todolist-json'),
    path('add/',add_todolist_item,name='add-todolist-item')

]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class MyWatchList(models.Model):
    watched = models.BooleanField()
    title = models.TextField()
    rating = models.IntegerField()
    release_date = models.DateField()
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Todolist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.TextField()
    title = models.TextField()
    description = models.TextField()
    isfinished = models.BooleanField(default=False)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem


# TODO: Create your views here.
def show_katalog(request):
    data_item_katalog = CatalogItem.objects.all()
    context = {
        'list_barang' : data_item_katalog,
        'nama' : 'Ramanti',
        'npm' : '2106638495'
    }
    return render(request, "katalog.html", context)

todolist/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from todolist.models import Todolist
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.core import serializers
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt



# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data = Todolist.objects.filter(user=request.user)
    username = request.user.username
    context = {
        'name' : username,
        'last_login': request.COOKIES['last_login'],
        'todolists': data
    }
    return render(request, "todolist.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

def create_task(request):
    if request.method == "POST":
        user = request.user
        date = request.POST.get("date")
        title = request.POST.get("title")
        description = request.POST.get("description")
        create_task = Todolist(user=user,date=date, title=title, description=description)
        create_task.save()
        return redirect('todolist:show_todolist')

    return render(request, "new_task.html")

@csrf_exempt
def update_task(request,id):
    item = Todolist.objects.get(pk=id)
    finished = not item.isfinished
    item.isfinished = finished
    item.save()
    return JsonResponse({"isfinished": finished})

@csrf_exempt
def delete(request,id):
    todolist = Todolist.objects.get(pk= id)
    todolist.delete()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def get_todolist_json(request):
    todolist_item = Todolist.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", todolist_item),content_type="application/json")

@login_required(login_url='/todolist/login/')
@csrf_exempt
def add_todolist_item(request):
    if request.method == "POST":
        user=request.user
        title = request.POST.get("title")
        description = request.POST.get("description")

        new_todolist = Todolist(user=user,title=title,description=description)
        new_todolist.save()

    return JsonResponse({"pk": new_todolist.pk, "fields":{"title":new_todolist.title,"description": new_todolist.description,"isfinished": new_todolist.isfinished}})



    

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_barang %}
    <tr>
      <th>{{barang.item_name}}</th>
      <th>{{barang.item_price}}</th>
      <th>{{barang.item_stock}}</th>
      <th>{{barang.rating}}</th>
      <th>{{barang.description}}</th>
      <th>{{barang.item_url}}</th>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 3 PBP</h1>

  <h5>Name: </h5>
  <p>Ramanti</p>

  <h5>Student ID: </h5>
  <p>2106638495</p>

  <table border="2">
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for film in list_film %}
    <tr>
      <th>{{film.watched}}</th>
      <th>{{film.title}}</th>
      <th>{{film.rating}}</th>
      <th>{{film.release_date}}</th>
      <th>{{film.review}}</th>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
</body>

</html>

todolist/templates/login.html
{% extends 'base.html' %} {% block meta %}
<title>Login</title>
{% endblock meta %} {% block content %}

<div class="login">

  <form method="POST" action="">
    {% csrf_token %}

    <section class="vh-100 gradient-custom">
      <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card bg-dark text-white" style="border-radius: 1rem;">
              <div class="card-body p-5 text-center">
    
                <div class="mb-md-5 mt-md-4 pb-5">
    
                  <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                  <p class="text-white-50 mb-5">Please enter your login and password!</p>
    
                  <div class="form-outline form-white mb-4">
                    <input type="text" name="username" placeholder="Username" class="form-control" />
                    <label class="form-label" for="usernamex">Username</label>
                  </div>
    
                  <div class="form-outline form-white mb-4">
                    <input type="password" name="password" placeholder="Password" class="form-control" />
                    <label class="form-label" for="passwordx">Password</label>
                  </div>
    
                  
    
                  <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>
    
                </div>
    
                <div>
                  <p class="mb-0">Don't have an account? <a href="{% url 'todolist:register' %}" class="text-white-50 fw-bold">Buat Akun</a>
                  </p>
                </div>
    
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </form>

  {% if messages %}
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %} Belum mempunyai akun?
  <a href="{% url 'todolist:register' %}">Buat Akun</a>
</div>



{% endblock content %}

todolist/templates/new_task.html
{% extends 'base.html' %} {% block content %}

<h1 class="m-5">What u gonna do</h1>



<div class="card w-50 m-5">
  <div class="card-body">
<form method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
    <tr>
        <td>Tanggal:</td>
        <td><input type="text" name="date" /></td>
      </tr>
    <tr>
        <td>Title:</td>
        <td><input type="text" name="title" /></td>
    </tr>
    <tr>
        <td>Description:</td>
        <td><input type="text" name="description" /></td>
    </tr>
    <tr>
        <td></td>
        <td><input type="submit" name="submit" value="Create" /></td>
    </tr>
  </table>
</form>

<button class="btn btn-primary btlgn-" ><a class="text-white" href="{% url 'todolist:logout' %}">Logout</a></button>
</div>
</div>
{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  


<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <section class="vh-100" style="background-color: #eee;">
              <div class="container h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                  <div class="col-lg-12 col-xl-11">
                    <div class="card text-black" style="border-radius: 25px;">
                      <div class="card-body p-md-5">
                        <div class="row justify-content-center">
                          <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
            
                            <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Registrasi Akun</p>
                         
                            <form class="mx-1 mx-md-4">
            
                              <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                  <input type="text" id="id_username"  name="username" class="form-control" />
                                  <label class="form-label" for="id_username">Username</label>
                                </div>
                              </div>
            
                              <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                  <input type="password" id="id_password1" name="password1" class="form-control" />
                                  <label class="form-label" for="id_password1">Password</label>
                                </div>
                              </div>
            
                              <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                  <input type="password" id="id_password2" name="password2" class="form-control" />
                                  <label class="form-label" for="id_password2">Repeat your password</label>
                                </div>
                              </div>
            
                    
            
                              <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                <input type="submit" class="btn btn-primary btlgn-"  name="submit" value="register"/>
                                
                              </div>
                              <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                <button class="btn btn-primary btlgn-" ><a class="text-white" href="{% url 'todolist:logout' %}">back</a></button>
                              </div>
                           
                              
                             
            
                            </form>
            
                          </div>
                          <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
            
                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                              class="img-fluid" alt="Sample image">
            
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

  </div>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  $(document).ready(function () {
    $.get(window.location.href + "json/", function (data) {
      for (idx = 0; idx < data.length; idx++) {getField(data[idx]);deleteField(data[idx]);updateField(data[idx]);}});

    $("#create-new").submit(function (event) {
      event.preventDefault();
      $.post(window.location.href + "add/", {
        title: $("#title").val(),
        description: $("#description").val(),
      }).done(function (data) {
        getField(data);
        deleteField(data);
        statusUpdate(data);
        $("#title").val(""), $("#description").val("");
        const sectionCards = document.getElementById("content");
        sectionCards.insertAdjacentHTML("beforestart", $(`#${data.pk}-card`));
      });
    });

    function getField(data) {
      $("#content").append(
        `
        <div id="${data.pk}-card" class="card hover-overlay" style="border-radius: 25rem; 15px; max-width:  height: fit-content; mx-5;background-color: #b094a2;">
            <div class="card-body p-3 ">
              <h5 class="card-title text-center m-2 ">${data.fields.title}</h5>
              <p class="card-text text-center m-2" style="font-size: 17px" >${data.fields.description}</p>
              <p class="card-text text-center m-2" style="font-size: 12px">${data.fields.date}</p>
              <p id="${data.pk}-status" class="card-text text-center m-2">${data.fields.isfinished ? "selesai": "belum selesai"}</p>
              <div class="flex justify-content-center text-center m-2">
                <a id="${data.pk}-update" class="btn btn btn-primary text-center m-2">Update Task</a>
                <a id="${data.pk}-delete" class="btn btn btn-danger text-center m-2">Delete Task</a>
              </div>
            </div>
          </div>
                  
                `
      );
    }

    function statusUpdate(data) {
      $(`#${data.pk}-update`).click(function () {
        $.post(window.location.href + `update-task/${data.pk}/`, {}).done(
          (res) => {
            const statusTodolist = res.isfinished
              ? "selesai"
              : "belum selesai";
            $(`#${data.pk}-status`).text(statusTodolist);
          }
        );
      });
    }

    function deleteField(data) {
      $(`#${data.pk}-delete`).click(function () {
        $.post(window.location.href + `delete-todolist/${data.pk}/`, {}).done(
          (res) => {
            $(`#${data.pk}-card`).fadeOut();
          }
        );
      });
    }

    //button close
  $(document).ready( function(){
    $('.btn-close').click( function(){
      $('.modal').toggle();
    })
  })

  //button n
  $(document).ready( function(){
    $('.add-task').click( function(){
      $('.modal').toggle();
    })
  })

  const modalButton = document.getElementById('add-btn');
  modalButton.click(() => {
    alert(12);
    $('.modal').toggle();
  })  
  });
</script>

  
<style>
  .card:hover{
    box-shadow: 4px 4px 2px rgb(108, 120, 130);
    transform: scale(1.05);
  }
</style>
{% endblock meta %}

{% block content %}

<nav class="navbar" style="background-color: #433030;">
   <h1 class="text-white  m-3">{{name}}'s TODOLIST</h1>
</nav>

  <h2 class="text-center m-5" style="font-weight: bold; font-size: larger;" > Just do this neverending todolist </h2>
<h5 class="m-2"> Sesi terakhir login:{{ last_login }}</h5>

<button id="add-btn" class="add-task btn btn-primary"> Add Task </button>
<button button type="button" class="btn btn-secondary m-3 " style="background-color: #2c1c21;">
  <a class="text-white text-decoration-none" href="{% url 'todolist:create-task' %}">Tambah Task Baru</a>
</button>




<!-- modal -->
<div class="modal w-25 " style="background-color: #a98181;">
  <h1 class="modal-title">Add New Task</h1>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  <form method="POST" action="" id="create-new">
  {% csrf_token %}
  <div class="flex flex-col m-2">
    <label class="form-label">Task</label>
    <input id="title" placeholder="Create task" class="task form-control" required >
  </div>

  <div class="flex flex-col m-1">
    <label class="form-label">Description</label>
    <input id="description" placeholder="Deskripsi task" class="description form-control" required>
  </div>
 <input type="submit" name="submit" value="create">
</form>
</div>
<div id="content" class="content"></div>





<button type="button" class="btn btn-secondary m-3" style="background-color: #2c1c21;">
  <a class="text-white text-decoration-none" href="{% url 'todolist:logout' %}">Logout</a></button>

{% endblock content %}